#!/bin/sh +x
### BEGIN INIT INFO
# Provides:          dsvr
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Domain Specific Routing
### END INIT INFO

DSVRPATH="/path/to/dsvr"
EXECUTABLEPATH="$DSVRPATH/dsvr.py"
INIPATH="/path/to/dsvr/config/dsvr.ini"
BLOCKLISTSRC="https://raw.githubusercontent.com/pi-hole/pi-hole/master/adlists.default"
BLOCKLISTOUTPUT="/path/to/dsvr/config/blacklist.txt"

SCRIPT="$EXECUTABLEPATH --file $INIPATH"
RUNAS=root

PIDNAME="dsvr.pid"
PIDFILE="/var/run/$PIDNAME"
LOGFILE=/var/log/dsvr.log

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 

  if [ ! -z "BLOCKLISTSRC" ]; then
    echo "Updating blocklist" >&2
    eval "$DSVRPATH/adlist-to-blacklist.py -i $BLOCKLISTSRC -o $BLOCKLISTOUTPUT" 
  fi

  echo 'Starting service.' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service.' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
   rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f dsvr remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac